.\" This file is distributed under the same license as the input-pad
.\" package.
.\" Copyright (C) Takao Fujiwara <takao.fujiwara1@gmail.com>, 2010.
.\"
.TH "INPUT-PAD" 1 "2010-07-09" "" ""
.SH NAME
input-pad \- On-screen Input Pad to Send Characters with Mouse

.SH "SYNOPSIS"
.B input-pad

.SH "DESCRIPTION"

.PP
input-pad is a tool to send a character on button to text applications.
It provides the GTK+ based GUI and can send characteres on the GTK+ buttons.

.PP
Homepage: http://code.google.com/p/input-pad/

.SH "SEE ALSO"
.BR ibus (1)
